name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests & Security
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: cacheese
          POSTGRES_PASSWORD: cacheese
          POSTGRES_DB: cacheese_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://cacheese:cacheese@localhost:5432/cacheese_test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up database
        run: bin/rails db:migrate

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

      - name: Run Brakeman
        run: bundle exec brakeman --no-pager

      - name: Run tests
        run: bundle exec rspec